# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currency',
            new_name='tokens',
        ),
    ]
