# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171021_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hash',
            field=models.CharField(default='81DBBQ837AERB0MYVTN5DG1BBL3B8XH5ILO7P84YPQQS81PFLGUN0QWHQHY1HJZ0', max_length=64),
        ),
    ]
