# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_account_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='client', max_length=64),
        ),
    ]
