# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ADE', max_length=64)),
                ('price', models.FloatField(default=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=100)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account')),
            ],
        ),
    ]
