# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_festival_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account'),
        ),
    ]
