# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171021_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterField(
            model_name='tickets',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account'),
        ),
    ]
