# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20171021_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name=homepage.models.Account)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Drinks')),
            ],
        ),
        migrations.AlterField(
            model_name='tickets',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account'),
        ),
    ]
